feat(controller): add rpc methods for controller
instill-ai/protobufs pull request #144
Opened 2023-03-13 07:32 UTC by heiruwu

Because

- support controller service for model resource state monitoring

This commit

- add rpc methods for controller
- update admin/private wording
- fix trailing whitespaces and end of file line

2023-03-14 05:35 UTC, pinglin commented on vdp/model/v1alpha/model_private_service.proto
> +    // ========== Admin API ==========
We probably wanna name these APIs `Private API`. Need to change this in other backend protobuf comment too. (cc'd @xiaofei-du)

2023-03-21 10:25 UTC, pinglin requested changes

2023-03-21 13:13 UTC, xiaofei-du requested changes

2023-03-21 13:13 UTC, xiaofei-du commented on vdp/controller/v1alpha/controller.proto
> +    }
agree

2023-03-21 13:13 UTC, xiaofei-du commented on vdp/model/v1alpha/model_public_service.proto
> +      get : "/v1alpha/{name=models/*/instances/*/watch}"
```suggestion
      get : "/v1alpha/{name=models/*/instances/*}/watch"
```

2023-03-21 13:13 UTC, xiaofei-du commented on vdp/controller/v1alpha/controller_service.proto
> +}
Can we follow how `pipeline/v1alpha/pipeline_public_service.proto` defines the service using the Google API annotations like `google.api.http` and `google.api.method_signature` to pin down the endpoint details?

2023-03-21 13:14 UTC, heiruwu commented on vdp/controller/v1alpha/controller.proto
> +    }
What I am thinking is, we refactored the `enum State` in each resources' proto to have only `STATE_ONLINE ` and `STATE_OFFLINE`, and only the `enum State` in controller.proto has these four states. `oneof` will definitely works too

2023-03-21 13:42 UTC, pinglin commented on vdp/controller/v1alpha/controller.proto
> +    }
That can certainly do but just not semantically straightforward for pipeline and connector to be `online/offline` compared with [`active/inactive`](https://www.instill.tech/docs/core-concepts/pipeline#state) and [`connected/disconnected`](https://www.instill.tech/docs/core-concepts/connector#state) respectively.

2023-03-21 14:13 UTC, heiruwu commented on vdp/controller/v1alpha/controller.proto
> +    }
Agree

2023-03-26 13:31 UTC, pinglin approved these changes
LGTM

2023-03-26 13:32 UTC, merged