feat: add method create model by GitHub
instill-ai/protobufs pull request #49
Opened 2022-03-25 09:24 UTC by Phelan164

Because

- It is convenient for users when creating a model from their GitHub repository

This commit

- Add a method to create a model by GitHub URL

2022-03-27 20:35 UTC, pinglin requested changes
Others look good to me.

2022-03-27 20:35 UTC, pinglin commented on instill/model/v1alpha/model.proto
> +  string github_url = 6;
```suggestion
  string github_url = 6 [ (google.api.field_behavior) = OUTPUT_ONLY ];
```
```suggestion
  // Model GitHub URL (has value when model created by CreateModelByGitHub and is empty when model created by CreateModelBinaryFileUpload)
  string github_url = 6 [ (google.api.field_behavior) = OUTPUT_ONLY ];
```

2022-03-29 13:38 UTC, Phelan164 commented on instill/model/v1alpha/model.proto
> +  string github_url = 6;
@pinglin I updated

2022-03-29 15:59 UTC, pinglin submitted a review, later dismissed
LGTM

2022-03-29 18:58 UTC, pinglin requested changes

2022-03-29 18:58 UTC, pinglin commented on instill/model/v1alpha/model.proto
> +  string commit = 6 [ (google.api.field_behavior) = OPTIONAL ];
Thinking of using `oneof` instead.

2022-03-29 20:25 UTC, pinglin submitted a review, later dismissed

2022-03-30 04:11 UTC, Phelan164 commented on instill/model/v1alpha/model.proto
> +  string commit = 6 [ (google.api.field_behavior) = OPTIONAL ];
@pinglin yes, agree

2022-03-30 11:02 UTC, pinglin approved these changes

2022-03-30 11:02 UTC, merged